version: '3.9'

services:
  backend:
    build: ./back_end
    container_name: backend_service
    ports:
      - "8000:8000"
    env_file:
      - ./back_end/.env
    depends_on:
      - db
    volumes:
      - ./back_end:/app
    restart: always
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maintenance_db
      MYSQL_USER: dhafin
      MYSQL_PASSWORD: dhafin123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  frontend:
    build: ./front_end/manufacturing/vite
    container_name: frontend_service
    ports:
      - "5173:5173"
    volumes:
      - ./front_end/manufacturing/vite:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000



volumes:
  db_data:
